[package]
name = "basm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
colored = "3.0.0"
ctrlc = "3.4.5"
logos = "0.15.0"
once_cell = "1.21.0"
prettytable-rs = "0.10.0"
term_size = "0.3.2"
