[package]
name = "basm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
colored = "3.0.0"
logos = "0.15.0"
once_cell = "1.20.3"
term_size = "0.3.2"
